### ISSUE TITLE
Crasher in BraceStyleListener

### ISSUE THREAD

**Issue by alexkent** [sleekbyte/tailor#264]
Tailor will crash when parsing this valid Swift:

    var foo: Bool {
        willSet { self.bar(newValue) }
    }

With a java trace:

    $ tailor tailor-crasher.swift 
    Exception in thread "main" java.lang.NullPointerException
	at com.sleekbyte.tailor.listeners.BraceStyleListener.verifyWillSetClauseBraceStyle(BraceStyleListener.java:312)
	at com.sleekbyte.tailor.listeners.BraceStyleListener.enterWillSetClause(BraceStyleListener.java:134)
	at com.sleekbyte.tailor.antlr.SwiftParser$WillSetClauseContext.enterRule(SwiftParser.java:5768)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:66)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:49)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at com.sleekbyte.tailor.Tailor.analyzeFiles(Tailor.java:285)
	at com.sleekbyte.tailor.Tailor.main(Tailor.java:344)

**Comment by alykhank** [comment]
Thanks for reporting @alexkent! I believe this issue was already fixed in #249, but you may be running v0.2.2 or earlier so please update to v0.3.0 and see if you can still reproduce.

**Comment by alexkent** [comment]
You're right I am using 0.2.2.
`brew upgrade tailor` tells me that 0.2.2 is current. What needs to happen for Homebrew to acknowledge 0.30 exists?

**Comment by alykhank** [comment]
`brew update && brew upgrade tailor` should do the trick :)

**Comment by alexkent** [comment]
great! thanks, my crashing file now passes :+1:

**Comment by alykhank** [comment]
Awesome!
